// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions; // 仅引入FirebaseOptions类
import 'package:flutter/foundation.dart' // 引入Flutter基础设施的部分功能
    show
        defaultTargetPlatform,
        kIsWeb,
        TargetPlatform;

/// 默认的 [FirebaseOptions]，用于你的Firebase应用。
///
/// 示例：
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // 根据当前平台返回相应的Firebase配置
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // 如果是Web平台
      return web;
    }
    switch (defaultTargetPlatform) {
      // 根据默认的目标平台判断
      case TargetPlatform.android: // 如果是Android平台
        return android;
      case TargetPlatform.iOS: // 如果是iOS平台
        return ios;
      case TargetPlatform.macOS: // 如果是macOS平台
        return macos;
      case TargetPlatform.windows: // 如果是Windows平台
        return windows;
      case TargetPlatform.linux: // 如果是Linux平台
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.', // Linux平台未配置提示
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.', // 其他未支持平台提示
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt_eeZ_xYXjKynKmx8xEQTyAMeQ6ryn8U',
    appId: '1:365204430823:android:89f6a94b271deaaa7c2742',
    messagingSenderId: '365204430823',
    projectId: 'job-test-b3034',
    databaseURL: 'https://job-test-b3034-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'job-test-b3034.firebasestorage.app',
  );

  // 针对Android平台的Firebase配置

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKhHgO12tWtRG_HR5mEg5lv-E5JCCpkIM',
    appId: '1:365204430823:ios:647ef6d8a15f41fa7c2742',
    messagingSenderId: '365204430823',
    projectId: 'job-test-b3034',
    databaseURL: 'https://job-test-b3034-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'job-test-b3034.firebasestorage.app',
    iosBundleId: 'com.example.kantankanri',
  );

  // 针对iOS平台的Firebase配置

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYXITOYDIF6UoR-QYXEnGhi3yu_9gYAf0',
    appId: '1:365204430823:web:4aecd03fcc391a987c2742',
    messagingSenderId: '365204430823',
    projectId: 'job-test-b3034',
    authDomain: 'job-test-b3034.firebaseapp.com',
    databaseURL: 'https://job-test-b3034-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'job-test-b3034.firebasestorage.app',
  );

  // 针对Web平台的Firebase配置

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKhHgO12tWtRG_HR5mEg5lv-E5JCCpkIM',
    appId: '1:365204430823:ios:07203588e6c438277c2742',
    messagingSenderId: '365204430823',
    projectId: 'job-test-b3034',
    databaseURL: 'https://job-test-b3034-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'job-test-b3034.firebasestorage.app',
    iosBundleId: 'com.example.job',
  );

  // 针对macOS平台的Firebase配置

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOlKCD8xu7yLURtoYjwCsQMK-6ghBLi9w',
    appId: '1:365204430823:web:590733b179f9d9d57c2742',
    messagingSenderId: '365204430823',
    projectId: 'job-test-b3034',
    authDomain: 'job-test-b3034.firebaseapp.com',
    databaseURL: 'https://job-test-b3034-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'job-test-b3034.firebasestorage.app',
  );

  // 针对Windows平台的Firebase配置
}